version: '3'

volumes:
  phpfpm-socket:

services:
  balancer:
    build: nginx-balancer/
    volumes:
      - ./nginx-balancer/conf/nginx/ktteam.conf:/etc/nginx/conf.d/ktteam.conf
    ports:
      - 80:80
  web:
    build: nginx/
    volumes:
      - ../web:/var/www/ktteam
      - ./nginx/conf/nginx/ktteam.conf:/etc/nginx/conf.d/ktteam.conf
      - phpfpm-socket:/var/run
  php-fpm:
    build: php-fpm/
    volumes:
      - ../web:/var/www/ktteam
      - ./php-fpm/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - phpfpm-socket:/var/run
