version: '3'

volumes:
  phpfpm-socket:

services:
  balancer:
    build: nginx-balancer/
    volumes:
      - ./nginx-balancer/conf/nginx/tasks-manager.conf:/etc/nginx/conf.d/tasks-manager.conf
    ports:
      - 80:80
  web-api:
    build: nginx-api/
    volumes:
      - ../web:/var/www/tasks-manager
      - ./nginx-api/conf/nginx/tasks-manager.conf:/etc/nginx/conf.d/tasks-manager.conf
      - phpfpm-socket:/var/run
  web-front:
    build: nginx-front/
    volumes:
      - ../web:/var/www/tasks-manager
      - ./nginx-front/conf/nginx/tasks-manager.conf:/etc/nginx/conf.d/tasks-manager.conf
  php-fpm:
    build: php-fpm/
    volumes:
      - ../web:/var/www/tasks-manager
      - ./php-fpm/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - phpfpm-socket:/var/run
